extends RefCounted

const SET := "Sanguo Spire"

const CARDS := {
	"杀": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 6 点伤害。",
		"Cost": 1,
		"_id": "sha",
		"_rarity": "common",
		"_base_damage": 6,
		"_evolves": ["doubleSha", "lifestealSha", "pierceSha"],
	},
	"连斩": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 4 点伤害，攻击 2 次。",
		"Cost": 1,
		"_id": "doubleSha",
		"_rarity": "rare",
		"_base_damage": 4,
		"_hits": 2,
	},
	"饮血杀": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 6 点伤害，若造成伤害则回复 3 点生命。",
		"Cost": 1,
		"_id": "lifestealSha",
		"_rarity": "rare",
		"_base_damage": 6,
		"_heal_after": 3,
	},
	"贯穿杀": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 7 点穿透伤害，无视护甲。",
		"Cost": 1,
		"_id": "pierceSha",
		"_rarity": "rare",
		"_base_damage": 7,
		"_pierce": true,
	},
	"防": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "获得 5 点护甲。",
		"Cost": 1,
		"_id": "fang",
		"_rarity": "common",
		"_block": 5,
	},
	"策": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "抽 2 张牌，然后弃 1 张牌。",
		"Cost": 1,
		"_id": "ce",
		"_rarity": "common",
		"_draw": 2,
		"_discard": 1,
	},
	"连弩": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "本回合所有【杀】费用变为 0。",
		"Cost": 1,
		"_id": "liannu",
		"_rarity": "rare",
		"_effect": "freeSha",
	},
	"强袭": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 12 点伤害；若已打出 2 张牌，额外 +6。",
		"Cost": 2,
		"_id": "qiangxi",
		"_rarity": "rare",
		"_base_damage": 12,
		"_combo_bonus": 6,
	},
	"计谋": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "敌人下回合攻击减半。切换到谋略姿态。",
		"Cost": 1,
		"_id": "jimou",
		"_rarity": "rare",
		"_effect": "weakenEnemy",
		"_stance": "tactic",
	},
	"洞察": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "抽 1 张牌，下一张攻击牌伤害 +4。",
		"Cost": 0,
		"_id": "dongcha",
		"_rarity": "common",
		"_draw": 1,
		"_effect": "nextAttackPlus4",
	},
	"爆发": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 20 点伤害，弃置所有手牌。",
		"Cost": 2,
		"_id": "baofa",
		"_rarity": "epic",
		"_base_damage": 20,
		"_discard_all_after": true,
	},
	"观策": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "查看牌堆顶 3 张，抽取其中 1 张。",
		"Cost": 1,
		"_id": "guance",
		"_rarity": "rare",
		"_effect": "scoutTop3Take1",
	},
	"坚壁": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "获得 8 点护甲。切换到防御姿态。",
		"Cost": 1,
		"_id": "jianbi",
		"_rarity": "common",
		"_block": 8,
		"_stance": "defense",
	},
	"牵引": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "抽 1 张牌。若抽到攻击牌，获得 1 点能量。",
		"Cost": 0,
		"_id": "qianyin",
		"_rarity": "rare",
		"_effect": "draw1IfAttackGain1",
	},
	"连环": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 4 点伤害；若本回合已打出技能牌，额外 +5。",
		"Cost": 1,
		"_id": "lianhuan",
		"_rarity": "common",
		"_base_damage": 4,
		"_after_skill_bonus": 5,
	},
	"识破": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "移除敌人护甲，抽 1 张牌。",
		"Cost": 1,
		"_id": "shipo",
		"_rarity": "rare",
		"_effect": "removeEnemyBlockDraw1",
	},
	"蓄力": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "接下来 2 张攻击牌伤害 +3。",
		"Cost": 1,
		"_id": "xuli",
		"_rarity": "rare",
		"_effect": "nextTwoAttackPlus3",
	},
	"破杀": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 9 点伤害。若敌人有护甲，额外 +8。",
		"Cost": 2,
		"_id": "posha",
		"_rarity": "rare",
		"_base_damage": 9,
		"_bonus_vs_block": 8,
	},
	"回府": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "回复 6 点生命。",
		"Cost": 1,
		"_id": "huifu",
		"_rarity": "common",
		"_heal": 6,
	},
	"破绽": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "施加 2 层印记。下一次攻击消耗印记并增伤。",
		"Cost": 1,
		"_id": "mark",
		"_rarity": "common",
		"_apply_mark": 2,
	},
	"火攻": {
		"Type": "skill",
		"Tags": ["skill"],
		"Abilities": "施加 3 层灼烧。敌人回合结束时受到灼烧伤害。",
		"Cost": 1,
		"_id": "ignite",
		"_rarity": "rare",
		"_apply_burn": 3,
	},
	"引爆": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 5 点伤害，并立即触发所有灼烧。",
		"Cost": 1,
		"_id": "detonate",
		"_rarity": "rare",
		"_base_damage": 5,
		"_detonate": true,
	},
	"孤注一掷": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 20 点伤害，50% 概率自身受到 15 点伤害。",
		"Cost": 0,
		"_id": "risk",
		"_rarity": "epic",
		"_base_damage": 20,
		"_risk_self": 15,
	},
	"破甲斩": {
		"Type": "attack",
		"Tags": ["attack"],
		"Abilities": "造成 12 点穿透伤害，无视护甲。",
		"Cost": 2,
		"_id": "pierce",
		"_rarity": "rare",
		"_base_damage": 12,
		"_pierce": true,
	},
}
